version: '2'
services:
    travispsqlesnoi18n-app:
        image: travispsqlesnoi18n
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://travispsqlesnoi18n-postgresql:5432/travisPsqlEsNoi18n
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://travispsqlesnoi18n-elasticsearch:9200
        ports:
            - 8080:8080
    travispsqlesnoi18n-postgresql:
        extends:
            file: postgresql.yml
            service: travispsqlesnoi18n-postgresql
    travispsqlesnoi18n-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: travispsqlesnoi18n-elasticsearch
